#!/bin/execlineb -P
# rc.init -

# Set the system clock to something sensible,
# to get coherent logs until the initial NTP exchange
foreground { s6-clock @400000005a58000000000000 }

if { s6-rc-init /run/service }

define target ok-multi-user

# Run the service manager.
# Call it twice because the first time may spuriously "timeout"
# due to the clock jumping forward.

loopwhilex -o 0 --
if -nt { s6-rc -- change ${target} }
if -n { s6-rc -- change ${target} }
/etc/s6/rc.rescue
